### ISSUE TITLE
TODO: Update Nex Wiki to use the right tag names for range vs melee

### ISSUE THREAD

**Issue by t8or** [t8or/runelite-recommended-equipment#3]
Update wiki and Recommended Equipment will be updated the following Thursday

**Comment by Koslas1** [comment]
Is this about the 2 Nex loadouts being called Default?
As Temposross have 5 loadouts, and they're all called Default instead of the names from the wiki

**Comment by adamk33n3r** [comment]
Yes, the `Recommended equipment` template tags need a `style` attribute. That's what the name comes from.

**Comment by t8or** [comment]
I have updated the README of this plugin to include how to make this update going forward. I have also updated[ Nex](https://oldschool.runescape.wiki/w/Nex/Strategies#Equipment) on the OSRS wiki to use the Ranged and Hybrid style tag. Closing this issue as done.

**Comment by Koslas1** [comment]
Would you be able to re open this issue. Or fix this somehow? I went through all the updated the style tags for recommended equipment. However the plugin still shows Default names. The wiki was edited 3 days ago, and it still hasn't updated in the plugin. Yes I have restarted Runelite since editing the wiki aswell
![image](https://github.com/user-attachments/assets/11ef2800-c4ad-40bb-9c69-aad65aea9d06)
![image](https://github.com/user-attachments/assets/382148cd-a090-4bbb-b083-026843f7e32b)

**Comment by t8or** [comment]
@Koslas1 No need to reopen! Your changes to the wiki worked! 

The plugin checks for changes once a week on Thursdays. As you updated the wiki on Saturday, the changes will appear this Thursday. I ran the update early and saw Tempeross updated in the plugin. Thanks for updating the wiki ❤️ 
![RuneLite - RuneLite - GIM T8or - 08-27-2024 at 08 58 AM](https://github.com/user-attachments/assets/26fd19d5-e13e-4590-9192-3607f83ab167)

**Comment by Koslas1** [comment]
I didn't expect it to be able to close out of an activity and go back into it and it was already updated without restarting Runelite.
But thanks for letting me know when it automatically updates, maybe add that into the README to say that it'll update the loadout names automatically every Thursday as I thought it was pulling the loadout names either when starting Runelite or clicking on the activity you wanted.
Also updating the wiki is always helpful, so will always do it if there's stuff I can update on the Wiki :)

**Comment by adamk33n3r** [comment]
@Koslas1 instead of having every user hitting the wiki multiple times (for each activity) every time they load runelite (I'm sure there's some rate limiting and we don't wanna ddos them lol), we decided to go with the approach of a separate process that runs weekly, does the wiki parsing, stores the data in a single file format on github that the plugin can pull from.

you can see that project and generated file here https://github.com/t8or/recequip-wiki-scraper/blob/master/recs/all.min.json

**Comment by adamk33n3r** [comment]
It _is_ stated in the discord that we sync the data weekly on Thursdays, but I understand not everybody will be looking there so it would be good to update the readme.
